import type { BiomeDef, MobSpawn } from './types';

// Surface, ocean and underground biomes. Land biomes are picked as the nearest climate point in
// (temperature, humidity, weirdness, mountains); all four fields are 3D noise over (x, z, w) plus
// an "ana bias" that varies fastest along W, so walking kata/ana changes the landscape.

const DAY: MobSpawn[] = [
  { mob: 'kata_sheep', weight: 12, group: [2, 4] },
  { mob: 'ana_cow', weight: 10, group: [2, 4] },
  { mob: 'hyperchicken', weight: 10, group: [2, 4] },
  { mob: 'tesseract_rabbit', weight: 6, group: [1, 3] },
];
const NIGHT: MobSpawn[] = [
  { mob: 'shambler', weight: 100, group: [1, 3] },
  { mob: 'bone_archer', weight: 80, group: [1, 2] },
  { mob: 'phase_creeper', weight: 60 },
  { mob: 'web_weaver', weight: 50 },
  { mob: 'ana_stalker', weight: 25 },
  { mob: 'kata_slime', weight: 20, group: [1, 2] },
];
const CAVE: MobSpawn[] = [
  { mob: 'shambler', weight: 60 },
  { mob: 'bone_archer', weight: 40 },
  { mob: 'hyperbat', weight: 30, group: [3, 6] },
  { mob: 'crystal_crawler', weight: 20 },
  { mob: 'ore_mimic', weight: 6 },
  { mob: 'phase_golem', weight: 4 },
];
const WATER: MobSpawn[] = [
  { mob: 'reef_squid', weight: 10, group: [2, 4] },
  { mob: 'lantern_fish', weight: 12, group: [3, 6] },
];
const STRUCT_COMMON = ['ruined_portal', 'ancient_ruins', 'stone_circle', 'campsite', 'standing_slabs', 'dungeon', 'hypermine', 'buried_treasure', 'ana_vault'];

export const BIOMES: BiomeDef[] = [
  // ---------------------------------------------------------------- temperate
  {
    name: 'meadow',
    displayName: 'Meadow',
    kind: 'land',
    climate: [0.5, 0.5, 0.55, 0.25],
    surface: 'grass',
    subsurface: 'loam',
    underwater: 'sand',
    stone: 'limestone',
    heightBias: 0,
    heightScale: 0.7,
    trees: [{ tree: 'oak', density: 0.0012 }],
    plants: [
      { block: 'tall_grass', density: 0.12 },
      { block: 'clover', density: 0.05 },
      { block: 'poppy', density: 0.012 },
      { block: 'cornflower', density: 0.01 },
    ],
    particles: [
      { kind: 'firefly', color: '#e8ff7a', rate: 3, glow: true, night: true },
      { kind: 'dust', color: '#fff6d0', rate: 1.5 },
    ],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#7aa9ff',
    fogColor: '#c3dbff',
    grassColor: '#79c05a',
    foliageColor: '#5aa832',
    waterColor: '#3f76e4',
    music: 'meadow',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['village_meadow', 'watchtower', 'cabin', ...STRUCT_COMMON],
  },
  {
    name: 'tesseract_forest',
    displayName: 'Tesseract Forest',
    kind: 'land',
    climate: [0.6, 0.7, 0.4, 0.35],
    surface: 'forest_turf',
    subsurface: 'forest_loam',
    underwater: 'loam',
    heightBias: 3,
    heightScale: 1.0,
    trees: [
      { tree: 'oak', density: 0.012 },
      { tree: 'big_oak', density: 0.003 },
    ],
    plants: [
      { block: 'fern', density: 0.1 },
      { block: 'tall_grass', density: 0.08 },
      { block: 'brown_mushroom', density: 0.01 },
      { block: 'bluebell', density: 0.01 },
      { block: 'lattice_fern', density: 0.05 },
    ],
    particles: [{ kind: 'leaf', color: '#5aa832', rate: 4 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#79a6f5',
    fogColor: '#b3cde6',
    grassColor: '#59ae30',
    foliageColor: '#3f8f20',
    waterColor: '#3d6ee0',
    music: 'forest',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['tesseract_grove_temple', 'cabin', 'witch_hut', ...STRUCT_COMMON],
  },
  {
    name: 'birch_glade',
    displayName: 'Birch Glade',
    kind: 'land',
    climate: [0.42, 0.55, 0.3, 0.3],
    surface: 'glade_turf',
    subsurface: 'loam',
    underwater: 'sand',
    heightBias: 1,
    heightScale: 0.8,
    trees: [{ tree: 'birch', density: 0.01 }],
    plants: [
      { block: 'tall_grass', density: 0.1 },
      { block: 'lily_of_valley', density: 0.015 },
      { block: 'tall_fern', density: 0.03 },
      { block: 'white_tulip', density: 0.02 },
    ],
    particles: [{ kind: 'leaf', color: '#d8d04a', rate: 3 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#80aefc',
    fogColor: '#c6dcff',
    grassColor: '#88bb67',
    foliageColor: '#80a755',
    waterColor: '#3f76e4',
    music: 'forest',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['cabin', ...STRUCT_COMMON],
  },
  {
    name: 'orchard_hills',
    displayName: 'Orchard Hills',
    kind: 'land',
    climate: [0.62, 0.48, 0.22, 0.56],
    surface: 'orchard_turf',
    subsurface: 'loam',
    underwater: 'gravel',
    terrain: 'hills',
    heightBias: 6,
    heightScale: 1.3,
    trees: [{ tree: 'apple', density: 0.006 }],
    plants: [
      { block: 'wild_wheat', density: 0.06 },
      { block: 'tall_grass', density: 0.08 },
      { block: 'poppy', density: 0.008 },
      { block: 'strawberry_bush', density: 0.012 },
    ],
    particles: [{ kind: 'petal', color: '#fff0f0', rate: 1.5 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#7cabff',
    fogColor: '#c6dcff',
    grassColor: '#8dc05a',
    foliageColor: '#6aa838',
    waterColor: '#3f76e4',
    music: 'meadow',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['village_orchard', 'windmill', ...STRUCT_COMMON],
  },
  {
    name: 'cherry_grove',
    displayName: 'Cherry Grove',
    kind: 'land',
    climate: [0.5, 0.58, 0.82, 0.72],
    surface: 'petal_turf',
    subsurface: 'loam',
    underwater: 'sand',
    heightBias: 8,
    heightScale: 1.2,
    trees: [{ tree: 'cherry', density: 0.006 }],
    plants: [
      { block: 'pink_petals', density: 0.12 },
      { block: 'lilac', density: 0.02 },
    ],
    particles: [{ kind: 'petal', color: '#f7a8c8', rate: 8 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#8fb2ff',
    fogColor: '#e8d4ec',
    grassColor: '#b6db61',
    foliageColor: '#b6db61',
    waterColor: '#5db7ef',
    music: 'cherry',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['stone_circle', 'campsite', ...STRUCT_COMMON],
  },
  {
    name: 'glass_marsh',
    displayName: 'Glass Marsh',
    kind: 'land',
    climate: [0.66, 0.93, 0.6, 0.04],
    surface: 'glass_turf',
    subsurface: 'marsh_mud',
    underwater: 'marsh_mud',
    terrain: 'marsh',
    heightBias: -4,
    heightScale: 0.25,
    trees: [{ tree: 'oak', density: 0.0008 }],
    plants: [
      { block: 'reeds', density: 0.18 },
      { block: 'glowcap', density: 0.02 },
      { block: 'marsh_marigold', density: 0.02 },
      { block: 'seagrass', density: 0.1, placement: 'underwater' },
    ],
    particles: [
      { kind: 'spore', color: '#7fffd0', rate: 14, glow: true },
      { kind: 'firefly', color: '#baffc8', rate: 4, glow: true, night: true },
    ],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#86b7c8',
    fogColor: '#9fc9bf',
    grassColor: '#6ab58e',
    foliageColor: '#5aa080',
    waterColor: '#5aa89a',
    music: 'marsh',
    mobs: { day: [...DAY, { mob: 'bog_frog', weight: 14, group: [2, 4] }, { mob: 'glass_moth', weight: 8 }], night: [...NIGHT, { mob: 'marsh_leech', weight: 40 }], water: WATER, cave: CAVE },
    structures: ['witch_hut', 'village_marsh', ...STRUCT_COMMON],
  },
  {
    name: 'mushroom_fen',
    displayName: 'Mushroom Fen',
    kind: 'land',
    climate: [0.5, 0.92, 0.92, 0.1],
    surface: 'mycelium',
    subsurface: 'fen_mud',
    underwater: 'fen_mud',
    heightBias: -1,
    heightScale: 0.5,
    trees: [
      { tree: 'red_giant_mushroom', density: 0.004 },
      { tree: 'brown_giant_mushroom', density: 0.004 },
    ],
    plants: [
      { block: 'red_mushroom', density: 0.03 },
      { block: 'brown_mushroom', density: 0.03 },
      { block: 'puffball', density: 0.02 },
    ],
    particles: [{ kind: 'spore', color: '#e8c8ff', rate: 10 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#9aa0d8',
    fogColor: '#b8a8d0',
    grassColor: '#8a9a6a',
    foliageColor: '#8a9a6a',
    waterColor: '#6a6ab0',
    music: 'marsh',
    mobs: { day: [{ mob: 'kata_slime', weight: 10 }], night: NIGHT, cave: CAVE },
    structures: STRUCT_COMMON,
  },
  // ---------------------------------------------------------------- cold
  {
    name: 'dense_taiga',
    displayName: 'Dense Taiga',
    kind: 'land',
    climate: [0.3, 0.72, 0.45, 0.5],
    surface: 'podzol',
    subsurface: 'podzol_dirt',
    underwater: 'gravel',
    heightBias: 4,
    heightScale: 1.1,
    trees: [{ tree: 'spruce', density: 0.014 }],
    plants: [
      { block: 'fern', density: 0.12 },
      { block: 'sweet_berry_bush', density: 0.01 },
      { block: 'tall_fern', density: 0.04 },
      { block: 'lingonberry', density: 0.015 },
    ],
    particles: [{ kind: 'leaf', color: '#3d5a3a', rate: 2 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#7fa1d0',
    fogColor: '#aebfd4',
    grassColor: '#6a9a5a',
    foliageColor: '#4a7a4a',
    waterColor: '#3d57d6',
    music: 'forest',
    mobs: { day: [...DAY, { mob: 'frost_fox', weight: 6 }], night: NIGHT, cave: CAVE },
    structures: ['village_taiga', 'cabin', ...STRUCT_COMMON],
  },
  {
    name: 'snow_taiga',
    displayName: 'Snow Taiga',
    kind: 'land',
    climate: [0.15, 0.65, 0.5, 0.4],
    surface: 'snowy_turf',
    subsurface: 'podzol_dirt',
    underwater: 'gravel',
    heightBias: 3,
    heightScale: 1.0,
    trees: [{ tree: 'frost_spruce', density: 0.01 }],
    plants: [
      { block: 'frost_fern', density: 0.05 },
      { block: 'snowdrop', density: 0.01 },
    ],
    particles: [{ kind: 'snow', color: '#ffffff', rate: 6 }],
    frozenWater: true,
    precipitation: 'snow',
    skyColor: '#a3bde6',
    fogColor: '#d8e4f2',
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3d57d6',
    music: 'snow',
    mobs: { day: [{ mob: 'frost_fox', weight: 10, group: [1, 2] }, { mob: 'tesseract_rabbit', weight: 6 }], night: [...NIGHT, { mob: 'frostbite_wraith', weight: 40 }], cave: CAVE },
    structures: ['igloo', 'village_snow', ...STRUCT_COMMON],
  },
  {
    name: 'ice_plains',
    displayName: 'Ice Plains',
    kind: 'land',
    climate: [0.05, 0.3, 0.4, 0.1],
    surface: 'snow',
    subsurface: 'permafrost',
    underwater: 'gravel',
    heightBias: -2,
    heightScale: 0.5,
    trees: [{ tree: 'frost_spruce', density: 0.0006 }],
    plants: [
      { block: 'snow_grass', density: 0.04 },
      { block: 'frostbloom', density: 0.006 },
    ],
    particles: [{ kind: 'snow', color: '#ffffff', rate: 8 }],
    frozenWater: true,
    precipitation: 'snow',
    skyColor: '#a9c3e8',
    fogColor: '#dfe9f5',
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3d57d6',
    music: 'snow',
    mobs: { day: [{ mob: 'frost_fox', weight: 8 }], night: [...NIGHT, { mob: 'frostbite_wraith', weight: 60 }], cave: CAVE },
    structures: ['igloo', ...STRUCT_COMMON],
  },
  {
    name: 'frost_spires',
    displayName: 'Frost Spires',
    kind: 'land',
    climate: [0.1, 0.45, 0.65, 0.85],
    surface: 'packed_snow',
    subsurface: 'frost_stone',
    underwater: 'gravel',
    stone: 'frost_stone',
    terrain: 'spires',
    heightBias: 10,
    heightScale: 1.4,
    trees: [{ tree: 'frost_spruce', density: 0.002 }],
    plants: [
      { block: 'ice_crystal_bud', density: 0.02 },
      { block: 'frost_moss', density: 0.05 },
    ],
    particles: [{ kind: 'snow', color: '#eaf6ff', rate: 12 }],
    frozenWater: true,
    precipitation: 'snow',
    skyColor: '#b0c8f0',
    fogColor: '#e4eef8',
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3d57d6',
    music: 'mountains',
    mobs: { day: [{ mob: 'frost_fox', weight: 6 }], night: [...NIGHT, { mob: 'frostbite_wraith', weight: 60 }], cave: CAVE },
    structures: ['watchtower', ...STRUCT_COMMON],
  },
  {
    name: 'weathered_steppe',
    displayName: 'Weathered Steppe',
    kind: 'land',
    climate: [0.35, 0.18, 0.45, 0.45],
    surface: 'steppe_turf',
    subsurface: 'gravelly_loam',
    underwater: 'gravel',
    stone: 'weathered_stone',
    terrain: 'steppe',
    heightBias: 5,
    heightScale: 0.9,
    trees: [{ tree: 'dead_tree', density: 0.0008 }],
    plants: [
      { block: 'feather_grass', density: 0.08 },
      { block: 'thistle', density: 0.01 },
    ],
    particles: [{ kind: 'dust', color: '#d8cfa8', rate: 6 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#8fb0e0',
    fogColor: '#d8d4c0',
    grassColor: '#a5a070',
    foliageColor: '#8f8a58',
    waterColor: '#4a78c8',
    music: 'steppe',
    mobs: { day: [...DAY, { mob: 'hyperhorse', weight: 6, group: [2, 4] }], night: NIGHT, cave: CAVE },
    structures: ['outpost', 'stone_circle', ...STRUCT_COMMON],
  },
  // ---------------------------------------------------------------- warm / hot
  {
    name: 'savanna',
    displayName: 'Savanna',
    kind: 'land',
    climate: [0.76, 0.3, 0.4, 0.3],
    surface: 'dry_turf',
    subsurface: 'loam',
    underwater: 'sand',
    stone: 'savanna_stone',
    heightBias: 2,
    heightScale: 0.7,
    trees: [{ tree: 'acacia', density: 0.0025 }],
    plants: [
      { block: 'tall_dry_grass', density: 0.18 },
      { block: 'savanna_shrub', density: 0.02 },
    ],
    particles: [{ kind: 'dust', color: '#e8d8a0', rate: 3 }],
    frozenWater: false,
    precipitation: 'none',
    skyColor: '#8fb8f0',
    fogColor: '#e0d8b8',
    grassColor: '#bfb755',
    foliageColor: '#aea42a',
    waterColor: '#3f76e4',
    music: 'savanna',
    mobs: { day: [...DAY, { mob: 'hyperhorse', weight: 8, group: [2, 5] }], night: NIGHT, cave: CAVE },
    structures: ['village_savanna', 'outpost', ...STRUCT_COMMON],
  },
  {
    name: 'bamboo_thicket',
    displayName: 'Bamboo Thicket',
    kind: 'land',
    climate: [0.74, 0.8, 0.55, 0.48],
    surface: 'grass',
    subsurface: 'jungle_soil',
    underwater: 'mud',
    heightBias: 4,
    heightScale: 1.1,
    trees: [
      { tree: 'bamboo', density: 0.05 },
      { tree: 'big_oak', density: 0.002 },
    ],
    plants: [
      { block: 'bamboo_shoot', density: 0.05 },
      { block: 'jungle_fern', density: 0.12 },
      { block: 'orchid', density: 0.01 },
    ],
    particles: [{ kind: 'firefly', color: '#d8ff7a', rate: 5, glow: true, night: true }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#78aee8',
    fogColor: '#a8d0b0',
    grassColor: '#59c93c',
    foliageColor: '#30bb0b',
    waterColor: '#3f9ae4',
    music: 'jungle',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['jungle_shrine', ...STRUCT_COMMON],
  },
  {
    name: 'dune_sea',
    displayName: 'Dune Sea',
    kind: 'land',
    climate: [0.9, 0.08, 0.35, 0.15],
    surface: 'dune_sand',
    subsurface: 'sand',
    underwater: 'sand',
    stone: 'sandstone',
    terrain: 'dunes',
    heightBias: 2,
    heightScale: 0.6,
    trees: [{ tree: 'cactus', density: 0.002 }],
    plants: [
      { block: 'dune_grass', density: 0.02 },
      { block: 'dead_bush', density: 0.008 },
      { block: 'desert_bloom', density: 0.004 },
    ],
    particles: [{ kind: 'dust', color: '#f0dc9c', rate: 10 }],
    frozenWater: false,
    precipitation: 'none',
    skyColor: '#9ec2ff',
    fogColor: '#eadcb6',
    grassColor: '#bfb755',
    foliageColor: '#aea42a',
    waterColor: '#32a598',
    music: 'desert',
    mobs: { day: [{ mob: 'dune_camel', weight: 6, group: [1, 2] }, { mob: 'tesseract_rabbit', weight: 4 }], night: [...NIGHT, { mob: 'hollow_husk', weight: 80 }], cave: CAVE },
    structures: ['desert_temple', 'village_desert', ...STRUCT_COMMON],
  },
  {
    name: 'sunscar_mesa',
    displayName: 'Sunscar Mesa',
    kind: 'land',
    climate: [0.88, 0.22, 0.65, 0.6],
    surface: 'red_sand',
    subsurface: 'terracotta_orange',
    underwater: 'red_sand',
    terrain: 'mesa',
    heightBias: 12,
    heightScale: 1.3,
    trees: [{ tree: 'dead_tree', density: 0.0006 }],
    plants: [
      { block: 'dead_bush', density: 0.02 },
      { block: 'mesa_flower', density: 0.006 },
      { block: 'mesa_brush', density: 0.02 },
    ],
    particles: [{ kind: 'dust', color: '#e89a60', rate: 6 }],
    frozenWater: false,
    precipitation: 'none',
    skyColor: '#9fc0f8',
    fogColor: '#e8c4a0',
    grassColor: '#90814d',
    foliageColor: '#9e814d',
    waterColor: '#3f76e4',
    music: 'desert',
    mobs: { day: [{ mob: 'tesseract_rabbit', weight: 4 }], night: [...NIGHT, { mob: 'hollow_husk', weight: 40 }], cave: CAVE },
    structures: ['hypermine', 'outpost', ...STRUCT_COMMON],
  },
  {
    name: 'bone_desert',
    displayName: 'Bone Desert',
    kind: 'land',
    climate: [0.95, 0.06, 0.85, 0.28],
    surface: 'bleached_sand',
    subsurface: 'sand',
    underwater: 'bleached_sand',
    stone: 'fossil_stone',
    heightBias: 1,
    heightScale: 0.6,
    trees: [{ tree: 'dead_tree', density: 0.0015 }],
    plants: [
      { block: 'bone_shrub', density: 0.02 },
      { block: 'dead_bush', density: 0.015 },
      { block: 'rib_weed', density: 0.01 },
    ],
    particles: [{ kind: 'dust', color: '#f4f0e0', rate: 8 }],
    frozenWater: false,
    precipitation: 'none',
    skyColor: '#b8c8e8',
    fogColor: '#f0e8d8',
    grassColor: '#bfb755',
    foliageColor: '#aea42a',
    waterColor: '#32a598',
    music: 'desert',
    mobs: { day: [], night: [...NIGHT, { mob: 'hollow_husk', weight: 80 }, { mob: 'bone_archer', weight: 60 }], cave: CAVE },
    structures: ['fossil_site', 'desert_temple', ...STRUCT_COMMON],
  },
  {
    name: 'volcanic_highlands',
    displayName: 'Volcanic Highlands',
    kind: 'land',
    climate: [0.88, 0.35, 0.55, 0.9],
    surface: 'ash_soil',
    subsurface: 'scoria',
    underwater: 'basalt',
    stone: 'basalt',
    terrain: 'volcanic',
    heightBias: 14,
    heightScale: 1.5,
    trees: [{ tree: 'dead_tree', density: 0.0008 }],
    plants: [
      { block: 'ember_fern', density: 0.03 },
      { block: 'charred_bush', density: 0.03 },
    ],
    particles: [
      { kind: 'ash', color: '#3a3636', rate: 14 },
      { kind: 'ember', color: '#ff7a2a', rate: 4, glow: true },
    ],
    frozenWater: false,
    precipitation: 'none',
    skyColor: '#a89a98',
    fogColor: '#8a7f7c',
    grassColor: '#7a7a4a',
    foliageColor: '#6a6a3a',
    waterColor: '#4a6a8a',
    music: 'volcanic',
    mobs: { day: [], night: [...NIGHT, { mob: 'lava_slime', weight: 30 }], cave: CAVE },
    structures: ['ruined_portal', ...STRUCT_COMMON],
  },
  {
    name: 'hollow_peaks',
    displayName: 'Hollow Peaks',
    kind: 'land',
    climate: [0.4, 0.5, 0.95, 0.86],
    surface: 'cloud_moss',
    subsurface: 'skystone',
    underwater: 'gravel',
    stone: 'hollow_stone',
    terrain: 'floating',
    heightBias: 8,
    heightScale: 1.3,
    trees: [
      { tree: 'birch', density: 0.003 },
      { tree: 'azalea', density: 0.003 },
    ],
    plants: [
      { block: 'sky_bloom', density: 0.02 },
      { block: 'tall_grass', density: 0.05 },
      { block: 'hanging_vine', density: 0.02 },
      { block: 'wind_bell', density: 0.02 },
    ],
    particles: [{ kind: 'mote', color: '#c8e8ff', rate: 8, glow: true }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#8ab8ff',
    fogColor: '#dcecff',
    grassColor: '#8ad08a',
    foliageColor: '#6ab86a',
    waterColor: '#5a9aff',
    music: 'mountains',
    mobs: { day: [{ mob: 'glass_moth', weight: 6 }, { mob: 'tesseract_rabbit', weight: 6 }], night: NIGHT, cave: CAVE },
    structures: ['sky_tower', 'lighthouse', ...STRUCT_COMMON],
  },
  // ---------------------------------------------------------------- oceans
  // ---------------------------------------------------------------- land (biome pass 2)
  {
    name: 'plains',
    displayName: 'Hyperplains',
    kind: 'land',
    climate: [0.55, 0.32, 0.32, 0.1],
    surface: 'plains_turf',
    subsurface: 'loam',
    underwater: 'sand',
    heightBias: -2,
    heightScale: 0.45,
    trees: [
      { tree: 'oak', density: 0.0004 }
    ],
    plants: [
      { block: 'tall_grass', density: 0.2 },
      { block: 'oxeye_daisy', density: 0.012 },
      { block: 'azure_bluet', density: 0.012 }
    ],
    particles: [{ kind: 'dust', color: '#fff6d0', rate: 2 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#78a8ff',
    fogColor: '#c3dbff',
    grassColor: '#91bd59',
    foliageColor: '#77ab2f',
    waterColor: '#3f76e4',
    music: 'meadow',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['village_meadow', 'watchtower', 'campsite', ...STRUCT_COMMON],
  },
  {
    name: 'flower_forest',
    displayName: 'Prism Flower Forest',
    kind: 'land',
    climate: [0.56, 0.62, 0.76, 0.3],
    surface: 'bloom_turf',
    subsurface: 'loam',
    underwater: 'sand',
    heightBias: 2,
    heightScale: 0.8,
    trees: [
      { tree: 'oak', density: 0.004 },
      { tree: 'birch', density: 0.003 }
    ],
    plants: [
      { block: 'prism_tulip', density: 0.03 },
      { block: 'allium', density: 0.03 },
      { block: 'peony', density: 0.02 },
      { block: 'tall_grass', density: 0.05 }
    ],
    particles: [{ kind: 'petal', color: '#ff9ae0', rate: 3 }, { kind: 'firefly', color: '#ffe07a', rate: 3, glow: true, night: true }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#7aa9ff',
    fogColor: '#d8d0f0',
    grassColor: '#79c05a',
    foliageColor: '#59ae30',
    waterColor: '#3f76e4',
    music: 'meadow',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['stone_circle', 'cabin', ...STRUCT_COMMON],
  },
  {
    name: 'dark_forest',
    displayName: 'Umbral Forest',
    kind: 'land',
    climate: [0.5, 0.86, 0.3, 0.38],
    surface: 'umbral_turf',
    subsurface: 'forest_loam',
    underwater: 'mud',
    heightBias: 2,
    heightScale: 0.9,
    trees: [
      { tree: 'dark_oak', density: 0.03 },
      { tree: 'red_giant_mushroom', density: 0.002 }
    ],
    plants: [
      { block: 'shadow_fern', density: 0.1 },
      { block: 'nightcap', density: 0.012 }
    ],
    particles: [{ kind: 'spore', color: '#b8a0ff', rate: 3, glow: true }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#6f8fc8',
    fogColor: '#5a6a58',
    grassColor: '#507a32',
    foliageColor: '#3a6a1f',
    waterColor: '#3a5a8a',
    music: 'forest',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['witch_hut', 'ancient_ruins', ...STRUCT_COMMON],
  },
  {
    name: 'jungle',
    displayName: 'Tangle Jungle',
    kind: 'land',
    climate: [0.84, 0.9, 0.35, 0.4],
    surface: 'jungle_turf',
    subsurface: 'loam',
    underwater: 'clay',
    heightBias: 4,
    heightScale: 1.1,
    trees: [
      { tree: 'jungle', density: 0.02 }
    ],
    plants: [
      { block: 'monstera', density: 0.12 },
      { block: 'jungle_bloom', density: 0.015 }
    ],
    particles: [{ kind: 'leaf', color: '#3f9a3a', rate: 4 }, { kind: 'firefly', color: '#c8ff6a', rate: 4, glow: true, night: true }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#78b0f0',
    fogColor: '#a8d8a8',
    grassColor: '#59c93c',
    foliageColor: '#30bb0b',
    waterColor: '#1a8a8a',
    music: 'jungle',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['jungle_shrine', ...STRUCT_COMMON],
  },
  {
    name: 'autumn_woods',
    displayName: 'Amber Woods',
    kind: 'land',
    climate: [0.42, 0.62, 0.74, 0.45],
    surface: 'leaf_litter',
    subsurface: 'loam',
    underwater: 'gravel',
    heightBias: 3,
    heightScale: 0.9,
    trees: [
      { tree: 'maple', density: 0.006 },
      { tree: 'amber_oak', density: 0.006 },
      { tree: 'birch', density: 0.002 }
    ],
    plants: [
      { block: 'amber_fern', density: 0.06 },
      { block: 'toadstool', density: 0.012 }
    ],
    particles: [{ kind: 'leaf', color: '#e8801a', rate: 6 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#8aa8e0',
    fogColor: '#e0c8a8',
    grassColor: '#a8b04a',
    foliageColor: '#c88a2a',
    waterColor: '#3f76e4',
    music: 'forest',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['cabin', 'watchtower', ...STRUCT_COMMON],
  },
  {
    name: 'scrubland',
    displayName: 'Dry Scrubland',
    kind: 'land',
    climate: [0.74, 0.16, 0.62, 0.3],
    surface: 'scrub_sand',
    subsurface: 'caliche',
    underwater: 'sand',
    heightBias: 1,
    heightScale: 0.55,
    trees: [
      { tree: 'juniper', density: 0.002 },
      { tree: 'dead_tree', density: 0.0005 }
    ],
    plants: [
      { block: 'sagebrush', density: 0.05 },
      { block: 'desert_marigold', density: 0.01 },
      { block: 'dead_bush', density: 0.01 }
    ],
    particles: [{ kind: 'dust', color: '#e0c890', rate: 5 }],
    frozenWater: false,
    precipitation: 'none',
    skyColor: '#9ec2ff',
    fogColor: '#e4d8b8',
    grassColor: '#bfb755',
    foliageColor: '#aea42a',
    waterColor: '#3f9fd4',
    music: 'desert',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['outpost', 'campsite', ...STRUCT_COMMON],
  },
  {
    name: 'lavender_fields',
    displayName: 'Lavender Downs',
    kind: 'land',
    climate: [0.46, 0.36, 0.7, 0.5],
    surface: 'downs_turf',
    subsurface: 'chalk',
    underwater: 'gravel',
    stone: 'chalk',
    heightBias: 3,
    heightScale: 0.7,
    trees: [
      { tree: 'birch', density: 0.0008 }
    ],
    plants: [
      { block: 'lavender', density: 0.08 },
      { block: 'heather', density: 0.05 },
      { block: 'tall_grass', density: 0.05 }
    ],
    particles: [{ kind: 'petal', color: '#b88ae8', rate: 3 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#8aa8ff',
    fogColor: '#dcd4f0',
    grassColor: '#8eb971',
    foliageColor: '#71a74d',
    waterColor: '#3f76e4',
    music: 'meadow',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['stone_circle', 'village_meadow', ...STRUCT_COMMON],
  },
  {
    name: 'stony_peaks',
    displayName: 'Stony Peaks',
    kind: 'land',
    climate: [0.36, 0.42, 0.38, 0.92],
    surface: 'peak_stone',
    subsurface: 'granite',
    underwater: 'gravel',
    stone: 'granite',
    heightBias: 12,
    heightScale: 1.5,
    trees: [
      { tree: 'spruce', density: 0.0008 }
    ],
    plants: [
      { block: 'edelweiss', density: 0.01 },
      { block: 'alpine_moss', density: 0.04 }
    ],
    particles: [{ kind: 'snow', color: '#ffffff', rate: 2 }],
    frozenWater: false,
    precipitation: 'snow',
    skyColor: '#8aaeff',
    fogColor: '#d0dae8',
    grassColor: '#8ab689',
    foliageColor: '#6a9a6a',
    waterColor: '#3f76e4',
    music: 'peaks',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['watchtower', ...STRUCT_COMMON],
  },
  {
    name: 'salt_flats',
    displayName: 'Salt Flats',
    kind: 'land',
    climate: [0.86, 0.12, 0.8, 0.04],
    surface: 'salt_crust',
    subsurface: 'salt_block',
    underwater: 'sand',
    terrain: 'flat',
    heightBias: -1,
    heightScale: 0.12,
    trees: [
      { tree: 'dead_tree', density: 0.0002 }
    ],
    plants: [
      { block: 'saltbush', density: 0.01 },
      { block: 'salt_bloom', density: 0.004 }
    ],
    particles: [{ kind: 'dust', color: '#ffffff', rate: 4 }],
    frozenWater: false,
    precipitation: 'none',
    skyColor: '#a8c8ff',
    fogColor: '#f0ece8',
    grassColor: '#c8c098',
    foliageColor: '#b0a878',
    waterColor: '#5fb8e0',
    music: 'desert',
    mobs: { day: DAY, night: NIGHT, cave: CAVE },
    structures: ['outpost', ...STRUCT_COMMON],
  },
  {
    name: 'ocean',
    displayName: 'Ocean',
    kind: 'ocean',
    climate: [0.5, 0.5, 0, 0],
    surface: 'sand',
    subsurface: 'sand',
    underwater: 'ocean_silt',
    heightBias: 0,
    heightScale: 1,
    trees: [{ tree: 'kelp', density: 0.004 }],
    plants: [
      { block: 'seagrass', density: 0.08, placement: 'underwater' },
      { block: 'sea_lettuce', density: 0.03, placement: 'underwater' },
      { block: 'tube_sponge', density: 0.01, placement: 'underwater' },
    ],
    particles: [{ kind: 'bubble', color: '#cfe8ff', rate: 3 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#7aa9ff',
    fogColor: '#c3dbff',
    grassColor: '#79c05a',
    foliageColor: '#5aa832',
    waterColor: '#3f76e4',
    music: 'ocean',
    mobs: { water: WATER, night: [{ mob: 'drowned_sentinel', weight: 30 }] },
    structures: ['shipwreck', 'sunken_monument', 'buried_treasure'],
  },
  {
    name: 'deep_ocean',
    displayName: 'Deep Ocean',
    kind: 'ocean',
    climate: [0.5, 0.95, 0, 0],
    surface: 'gravel',
    subsurface: 'gravel',
    underwater: 'abyssal_mud',
    heightBias: 0,
    heightScale: 1,
    trees: [{ tree: 'kelp', density: 0.002 }],
    plants: [
      { block: 'seagrass', density: 0.03, placement: 'underwater' },
      { block: 'deep_anemone', density: 0.01, placement: 'underwater' },
      { block: 'glow_polyp', density: 0.006, placement: 'underwater' },
    ],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#7aa9ff',
    fogColor: '#b8d0f8',
    grassColor: '#79c05a',
    foliageColor: '#5aa832',
    waterColor: '#2f5acc',
    music: 'ocean',
    mobs: { water: WATER, night: [{ mob: 'drowned_sentinel', weight: 50 }] },
    structures: ['sunken_monument', 'shipwreck'],
  },
  {
    name: 'frozen_ocean',
    displayName: 'Frozen Ocean',
    kind: 'ocean',
    climate: [0.05, 0.6, 0, 0],
    surface: 'gravel',
    subsurface: 'gravel',
    underwater: 'rime_gravel',
    heightBias: 0,
    heightScale: 1,
    trees: [{ tree: 'frost_kelp', density: 0.003 }],
    plants: [
      { block: 'frost_anemone', density: 0.01, placement: 'underwater' },
      { block: 'brine_weed', density: 0.04, placement: 'underwater' },
    ],
    particles: [{ kind: 'snow', color: '#ffffff', rate: 6 }],
    frozenWater: true,
    precipitation: 'snow',
    skyColor: '#a9c3e8',
    fogColor: '#dfe9f5',
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3938c9',
    music: 'snow',
    mobs: { water: WATER, night: [{ mob: 'frostbite_wraith', weight: 20 }] },
    structures: ['shipwreck', 'igloo'],
  },
  {
    name: 'coral_shallows',
    displayName: 'Coral Shallows',
    kind: 'ocean',
    climate: [0.85, 0.2, 0, 0],
    surface: 'sea_sand',
    subsurface: 'sea_sand',
    underwater: 'sea_sand',
    heightBias: 6,
    heightScale: 1,
    trees: [],
    plants: [
      { block: 'coral_red', density: 0.02, placement: 'underwater' },
      { block: 'coral_yellow', density: 0.02, placement: 'underwater' },
      { block: 'coral_blue', density: 0.015, placement: 'underwater' },
      { block: 'coral_pink', density: 0.02, placement: 'underwater' },
      { block: 'coral_fan_red', density: 0.04, placement: 'underwater' },
      { block: 'coral_fan_pink', density: 0.04, placement: 'underwater' },
      { block: 'coral_fan_yellow', density: 0.03, placement: 'underwater' },
      { block: 'seagrass', density: 0.1, placement: 'underwater' },
    ],
    particles: [{ kind: 'bubble', color: '#e0f8ff', rate: 5 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#80b8ff',
    fogColor: '#c8e8ff',
    grassColor: '#79c05a',
    foliageColor: '#5aa832',
    waterColor: '#43d5ee',
    music: 'ocean',
    mobs: { water: [...WATER, { mob: 'lantern_fish', weight: 20, group: [4, 8] }] },
    structures: ['shipwreck', 'buried_treasure'],
  },
  {
    name: 'kelp_deep',
    displayName: 'Kelp Deep',
    kind: 'ocean',
    climate: [0.45, 0.75, 0, 0],
    surface: 'dark_gravel',
    subsurface: 'gravel',
    underwater: 'dark_gravel',
    stone: 'tidestone',
    heightBias: -2,
    heightScale: 1,
    trees: [{ tree: 'kelp', density: 0.04 }],
    plants: [
      { block: 'seagrass', density: 0.15, placement: 'underwater' },
      { block: 'bladderwrack', density: 0.05, placement: 'underwater' },
      { block: 'sea_grape', density: 0.012, placement: 'underwater' },
    ],
    particles: [{ kind: 'bubble', color: '#cfe8ff', rate: 4 }],
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#7aa9ff',
    fogColor: '#b0d0e8',
    grassColor: '#79c05a',
    foliageColor: '#5aa832',
    waterColor: '#2f6ab8',
    music: 'ocean',
    mobs: { water: [...WATER, { mob: 'reef_squid', weight: 15, group: [2, 5] }], night: [{ mob: 'drowned_sentinel', weight: 40 }] },
    structures: ['sunken_monument', 'shipwreck'],
  },
  // ---------------------------------------------------------------- underground
  {
    name: 'lush_caves',
    displayName: 'Lush Caves',
    kind: 'underground',
    climate: [0.85, 0.4, 0.5, 0],
    surface: 'moss_block',
    subsurface: 'clay',
    underwater: 'clay',
    heightBias: 0,
    heightScale: 1,
    trees: [{ tree: 'azalea', density: 0.004 }],
    plants: [
      { block: 'cave_fern', density: 0.12, placement: 'floor' },
      { block: 'glow_berries', density: 0.05, placement: 'ceiling' },
      { block: 'spore_blossom', density: 0.01, placement: 'ceiling' },
      { block: 'hanging_vine', density: 0.05, placement: 'ceiling' },
    ],
    particles: [{ kind: 'spore', color: '#ffb0e0', rate: 6, glow: true }],
    frozenWater: false,
    precipitation: 'none',
    skyColor: '#3a4a3a',
    fogColor: '#2a3a2a',
    grassColor: '#79c05a',
    foliageColor: '#5aa832',
    waterColor: '#3f9a8a',
    music: 'lush',
    mobs: { cave: [{ mob: 'glass_moth', weight: 10 }, { mob: 'bog_frog', weight: 6 }, ...CAVE] },
    structures: [],
  },
  {
    name: 'dripstone_caves',
    displayName: 'Dripstone Caves',
    kind: 'underground',
    climate: [0.15, 0.5, 0.5, 0],
    surface: 'dripstone_block',
    subsurface: 'dripstone_block',
    underwater: 'dripstone_block',
    ceiling: 'dripstone_block',
    heightBias: 0,
    heightScale: 1,
    trees: [],
    plants: [
      { block: 'pointed_dripstone', density: 0.12, placement: 'floor' },
      { block: 'pointed_dripstone', density: 0.14, placement: 'ceiling' },
      { block: 'cave_lichen', density: 0.05, placement: 'floor' },
    ],
    particles: [{ kind: 'dust', color: '#a8886a', rate: 3 }],
    frozenWater: false,
    precipitation: 'none',
    skyColor: '#3a3430',
    fogColor: '#2a2420',
    grassColor: '#79c05a',
    foliageColor: '#5aa832',
    waterColor: '#3f76e4',
    music: 'caves',
    mobs: { cave: CAVE },
    structures: [],
  },
  {
    name: 'silent_layer',
    displayName: 'The Silent Layer',
    kind: 'underground',
    climate: [0.5, 0.9, 1.0, 0],
    surface: 'echo_moss',
    subsurface: 'hush_stone',
    underwater: 'hush_stone',
    ceiling: 'hush_stone',
    stone: 'silent_shale',
    heightBias: 0,
    heightScale: 1,
    trees: [],
    plants: [
      { block: 'echo_sprout', density: 0.06, placement: 'floor' },
      { block: 'echo_vine', density: 0.04, placement: 'ceiling' },
    ],
    particles: [{ kind: 'mote', color: '#35f0e0', rate: 5, glow: true }],
    frozenWater: false,
    precipitation: 'none',
    skyColor: '#0a1014',
    fogColor: '#060a0e',
    grassColor: '#79c05a',
    foliageColor: '#5aa832',
    waterColor: '#1a3a4a',
    music: 'silent',
    mobs: { cave: [{ mob: 'lurker', weight: 1 }] },
    structures: ['deep_silent_vault'],
  },
];
