import type { BiomeDef } from './types';

// Phase 1 ships a small test set so the engine can exercise biome-tinted sky/fog,
// snow vs rain and frozen water. Phase 2 replaces this with the full 24-biome table.
export const BIOMES: BiomeDef[] = [
  {
    name: 'meadow',
    displayName: 'Meadow',
    temperature: 0.55,
    humidity: 0.45,
    surface: 'grass',
    subsurface: 'dirt',
    underwater: 'sand',
    heightBias: 0,
    heightScale: 0.8,
    treeDensity: 0.0015,
    grassDensity: 0.1,
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#7aa9ff',
    fogColor: '#c3dbff',
    grassColor: '#79c05a',
    foliageColor: '#5aa832',
    waterColor: '#3f76e4',
  },
  {
    name: 'tesseract_forest',
    displayName: 'Tesseract Forest',
    temperature: 0.6,
    humidity: 0.8,
    surface: 'grass',
    subsurface: 'dirt',
    underwater: 'dirt',
    heightBias: 4,
    heightScale: 1.1,
    treeDensity: 0.012,
    grassDensity: 0.18,
    frozenWater: false,
    precipitation: 'rain',
    skyColor: '#79a6f5',
    fogColor: '#b3cde6',
    grassColor: '#59ae30',
    foliageColor: '#3f8f20',
    waterColor: '#3d6ee0',
  },
  {
    name: 'ice_plains',
    displayName: 'Ice Plains',
    temperature: 0.08,
    humidity: 0.4,
    surface: 'snow',
    subsurface: 'dirt',
    underwater: 'gravel',
    heightBias: -2,
    heightScale: 0.6,
    treeDensity: 0.0006,
    grassDensity: 0,
    frozenWater: true,
    precipitation: 'snow',
    skyColor: '#a9c3e8',
    fogColor: '#dfe9f5',
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3d57d6',
  },
  {
    name: 'dune_sea',
    displayName: 'Dune Sea',
    temperature: 0.92,
    humidity: 0.1,
    surface: 'sand',
    subsurface: 'sandstone',
    underwater: 'sand',
    heightBias: 2,
    heightScale: 0.7,
    treeDensity: 0,
    grassDensity: 0,
    frozenWater: false,
    precipitation: 'none',
    skyColor: '#9ec2ff',
    fogColor: '#eadcb6',
    grassColor: '#bfb755',
    foliageColor: '#aea42a',
    waterColor: '#32a598',
  },
];
