import type { BlockDef } from './types';

// Block registry data. Order defines numeric ids (air must stay first = id 0).
// Numeric ids are an in-memory detail; saves store names.
export const BLOCKS: BlockDef[] = [
  { name: 'air', render: 'invisible', solid: false, textures: {}, replaceable: true },
  { name: 'bedrock', render: 'opaque', solid: true, textures: { all: 'bedrock' }, hardness: -1 },
  { name: 'stone', render: 'opaque', solid: true, textures: { all: 'stone' }, hardness: 1.5 },
  { name: 'cobblestone', render: 'opaque', solid: true, textures: { all: 'cobblestone' }, hardness: 2 },
  { name: 'smooth_stone', render: 'opaque', solid: true, textures: { all: 'smooth_stone' }, hardness: 2 },
  { name: 'dirt', render: 'opaque', solid: true, textures: { all: 'dirt' }, hardness: 0.5 },
  {
    name: 'grass',
    displayName: 'Grass Block',
    render: 'opaque',
    solid: true,
    textures: { top: 'grass_top', side: 'grass_side', bottom: 'dirt' },
    biomeTint: 1,
    hardness: 0.6,
  },
  { name: 'sand', render: 'opaque', solid: true, textures: { all: 'sand' }, hardness: 0.5 },
  { name: 'sandstone', render: 'opaque', solid: true, textures: { all: 'sandstone' }, hardness: 0.8 },
  { name: 'gravel', render: 'opaque', solid: true, textures: { all: 'gravel' }, hardness: 0.6 },
  { name: 'snow', displayName: 'Snow Block', render: 'opaque', solid: true, textures: { all: 'snow' }, hardness: 0.2 },
  {
    name: 'ice',
    render: 'translucent',
    solid: true,
    textures: { all: 'ice' },
    tint: '#a8cbff',
    alpha: 0.55,
    lightOpacity: 2,
    hardness: 0.5,
  },
  { name: 'clay', render: 'opaque', solid: true, textures: { all: 'clay' }, hardness: 0.6 },
  {
    name: 'water',
    render: 'fluid',
    solid: false,
    fluid: 'water',
    shape: 'fluid',
    textures: { all: 'water' },
    tint: '#3f76e4',
    alpha: 0.5,
    lightOpacity: 2,
    replaceable: true,
  },
  {
    name: 'lava',
    render: 'fluid',
    solid: false,
    fluid: 'lava',
    shape: 'fluid',
    textures: { all: 'lava' },
    tint: '#ff7a1a',
    alpha: 1,
    emission: 15,
    lightOpacity: 15,
    damage: 4,
    replaceable: true,
  },
  { name: 'log', displayName: 'Tesseract Log', render: 'opaque', solid: true, textures: { top: 'log_top', bottom: 'log_top', side: 'log_side' }, hardness: 2 },
  {
    name: 'leaves',
    render: 'cutout',
    solid: true,
    textures: { all: 'leaves' },
    biomeTint: 2,
    lightOpacity: 1,
    opaque: false,
    hardness: 0.2,
  },
  { name: 'planks', render: 'opaque', solid: true, textures: { all: 'planks' }, hardness: 2 },
  {
    name: 'glass',
    render: 'translucent',
    solid: true,
    textures: { all: 'glass' },
    tint: '#e6f6ff',
    alpha: 0.14,
    hardness: 0.3,
  },
  { name: 'lumen', displayName: 'Lumen Block', render: 'opaque', solid: true, textures: { all: 'lumen' }, emission: 15, hardness: 0.3 },
  {
    name: 'torch',
    render: 'opaque',
    solid: false,
    shape: 'torch',
    opaque: false,
    textures: { all: 'torch' },
    emission: 14,
    replaceable: false,
    hardness: 0,
  },
  { name: 'coal_ore', render: 'opaque', solid: true, textures: { all: 'coal_ore' }, hardness: 3 },
  { name: 'iron_ore', render: 'opaque', solid: true, textures: { all: 'iron_ore' }, hardness: 3 },
  {
    name: 'hyperite_ore',
    displayName: 'Hyperite Ore',
    render: 'opaque',
    solid: true,
    textures: { all: 'hyperite_ore' },
    emission: 7,
    hardness: 4,
  },
  { name: 'obsidian', render: 'opaque', solid: true, textures: { all: 'obsidian' }, hardness: 50 },
  {
    name: 'stone_slab',
    render: 'opaque',
    solid: true,
    shape: 'slab',
    opaque: false,
    textures: { all: 'smooth_stone' },
    hardness: 2,
  },
  {
    name: 'stone_stairs',
    render: 'opaque',
    solid: true,
    shape: 'stairs',
    opaque: false,
    textures: { all: 'cobblestone' },
    hardness: 2,
  },
  {
    name: 'ladder',
    render: 'cutout',
    solid: true,
    shape: 'ladder',
    opaque: false,
    climbable: true,
    textures: { all: 'ladder' },
    hardness: 0.4,
  },
  {
    name: 'portal',
    displayName: 'Portal Membrane',
    render: 'translucent',
    solid: false,
    textures: { all: 'portal' },
    tint: '#9b4dff',
    alpha: 0.6,
    emission: 11,
    hardness: -1,
  },
  { name: 'bricks', render: 'opaque', solid: true, textures: { all: 'bricks' }, hardness: 2 },
  {
    name: 'tall_grass',
    render: 'cutout',
    solid: false,
    shape: 'plant',
    opaque: false,
    textures: { all: 'tall_grass' },
    biomeTint: 1,
    replaceable: true,
    hardness: 0,
  },
  { name: 'marker_x', displayName: '+X Marker', render: 'opaque', solid: true, textures: { all: 'marker_x' }, hardness: 0.5 },
  { name: 'marker_y', displayName: '+Y Marker', render: 'opaque', solid: true, textures: { all: 'marker_y' }, hardness: 0.5 },
  { name: 'marker_z', displayName: '+Z Marker', render: 'opaque', solid: true, textures: { all: 'marker_z' }, hardness: 0.5 },
  { name: 'marker_w', displayName: '+W Marker', render: 'opaque', solid: true, textures: { all: 'marker_w' }, hardness: 0.5 },
];
